export type formDataType = {
    title: string,
    email_address: string,
    website: string,
    place_name: string,
    address_line_1: string,
    address_line_2: string,
    postcode: string,
    lat: string,
    lng: string,
    short_description: string,
    from_price: string,
    price_to: string,
    header_image_data: string,
};
