export const dataArray = [

    // id: 1,
    // title: "Title 1",
    // email: "yaso@example.com",
    // icon: "icon1.png",
 
      { image: "image11.jpg", name: "Title 11", owner: "Owner 11" },
      { image: "image12.jpg", name: "Title 12", owner: "Owner 12" },
      { image: "image13.jpg", name: "Title 13", owner: "Owner 13" },
      { image: "image14.jpg", name: "Title 14", owner: "Owner 14" },
      { image: "image15.jpg", name: "Title 15", owner: "Owner 15" },
      { image: "image16.jpg", name: "Title 16", owner: "Owner 16" },
      { image: "image17.jpg", name: "Title 17", owner: "Owner 17" },
      { image: "image18.jpg", name: "Title 18", owner: "Owner 18" },
      { image: "image19.jpg", name: "Title 19", owner: "Owner 19" },
      { image: "image20.jpg", name: "Title 20", owner: "Owner 20" },
    

]
//   {
//     // id: 2,
//     // title: "Title 2",
//     // email: "example2@example.com",
//     // icon: "icon2.png",
//     titles: [
//       { image: "image11.jpg", name: "Title 11", owner: "Owner 11" },
//       { image: "image12.jpg", name: "Title 12", owner: "Owner 12" },
//       { image: "image13.jpg", name: "Title 13", owner: "Owner 13" },
//       { image: "image14.jpg", name: "Title 14", owner: "Owner 14" },
//       { image: "image15.jpg", name: "Title 15", owner: "Owner 15" },
//       { image: "image16.jpg", name: "Title 16", owner: "Owner 16" },
//       { image: "image17.jpg", name: "Title 17", owner: "Owner 17" },
//       { image: "image18.jpg", name: "Title 18", owner: "Owner 18" },
//       { image: "image19.jpg", name: "Title 19", owner: "Owner 19" },
//       { image: "image20.jpg", name: "Title 20", owner: "Owner 20" },
//     ],
//   },
//   {
//     id: 3,
//     title: "Title 3",
//     email: "example3@example.com",
//     icon: "icon3.png",
//     titles: [
//       { image: "image11.jpg", name: "Title 11", owner: "Owner 11" },
//       { image: "image12.jpg", name: "Title 12", owner: "Owner 12" },
//       { image: "image13.jpg", name: "Title 13", owner: "Owner 13" },
//       { image: "image14.jpg", name: "Title 14", owner: "Owner 14" },
//       { image: "image15.jpg", name: "Title 15", owner: "Owner 15" },
//       { image: "image16.jpg", name: "Title 16", owner: "Owner 16" },
//       { image: "image17.jpg", name: "Title 17", owner: "Owner 17" },
//       { image: "image18.jpg", name: "Title 18", owner: "Owner 18" },
//       { image: "image19.jpg", name: "Title 19", owner: "Owner 19" },
//       { image: "image20.jpg", name: "Title 20", owner: "Owner 20" },
//     ],
//   },
//   {
//     id: 4,
//     title: "Title 4",
//     email: "example4@example.com",
//     icon: "icon4.png",
//     titles: [{ image: "image4.jpg", name: "Title4", owner: "Owner4" }],
//   },
//   {
//     id: 5,
//     title: "Title 5",
//     email: "example5@example.com",
//     icon: "icon5.png",
//     titles: [{ image: "image5.jpg", name: "Title5", owner: "Owner5" }],
//   },
//   {
//     id: 6,
//     title: "Title 6",
//     email: "example6@example.com",
//     icon: "icon6.png",
//     titles: [{ image: "image6.jpg", name: "Title6", owner: "Owner6" }],
//   },
//   {
//     id: 7,
//     title: "Title 7",
//     email: "example7@example.com",
//     icon: "icon7.png",
//     titles: [{ image: "image7.jpg", name: "Title7", owner: "Owner7" }],
//   },
//   {
//     id: 8,
//     title: "Title 8",
//     email: "example8@example.com",
//     icon: "icon8.png",
//     titles: [{ image: "image8.jpg", name: "Title8", owner: "Owner8" }],
//   },
//   {
//     id: 9,
//     title: "Title 9",
//     email: "example9@example.com",
//     icon: "icon9.png",
//     titles: [{ image: "image9.jpg", name: "Title9", owner: "Owner9" }],
//   },
//   {
//     id: 10,
//     title: "Title 10",
//     email: "example10@example.com",
//     icon: "icon10.png",
//     titles: [{ image: "image10.jpg", name: "Title10", owner: "Owner10" }],
//   },
// ];
